title: kyr's page
author: kye
email: ryk2100@163.com
description: > # this means to ignore newlines until "baseurl:"
    website list

# social links
github_username:  https://github.com/ryk072018

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
